name: Build and Push Docker Image

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Log in to docker.io
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push bitwarden-backup
      uses: docker/build-push-action@v6
      with:
        context: bitwarden-backup
        push: true
        tags: ${{ secret.DOCKERHUB_USERNAME }}/bitwarden-backup:latest
    
